Add (void) to function prototypes in test_kyber.c
The following compilation errors occur without this change which is default on current clang release (macos)
kyber/ref/test_kyber.c:62:35: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]